version: '3'
services:
  app:
    command: meteor
    image: node:latest
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/meteor
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    build: ./
  
  mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
